### ISSUE TITLE
Old files from SRTM15_v2.1 in test server?

### ISSUE THREAD

**Issue by Esteban82** [GenericMappingTools/gmtserver-admin#159] opened 2022-08-19 02:26 UTC
I was looking in the test server and I found these two folders. I think that the first is an old version (2.1) of the SRTM15, and thus could be deleted. 

http://test.generic-mapping-tools.org/server/earth/earth_relief2.1/
http://test.generic-mapping-tools.org/server/earth/earth_relief/

**Comment by PaulWessel** [comment] 2022-08-19 15:02
I think we still have a conversation of what to do with tests.  Having 60 tests fail each time we update earth_relief means lots of extra work on growth of the dvc system.  I think @maxrjones and I were discussing maybe using a test server when running the tests so that we would get a stable set of remote grids to avoid this problem.  These files would ideally not be mirrored across to all servers.

**Comment by Esteban82** [comment] 2023-01-04 11:59
I think that this issue can be closed.

**Comment by PaulWessel** [comment] 2023-08-23 11:43
OK, woken on this but copying from Hawaii to Oslo is a, well, bit slow!

**Comment by PaulWessel** [comment] 2023-08-23 12:23
Yes, GMT_USER_DIR=~/.gmt-candidate will use that dir for all "./gmt" work (look for data, create session). So we can let our remote-data test scripts set that, for instance.

OK, candidate is a good name.

**Comment by seisman** [comment] 2023-08-23 14:24
> Since our hope is that Geoscope can be persuaded to take over the hosting

Do you mean "EarthScope" (https://www.earthscope.org/)?
 
> 3. I see no point keeping the _data_6.0_, _data_6.1_ directories as gmtserver just fills up.

Yes, actually the name "data_6.2" also makes no sense to me. We should simply name it "data", without any version string.

The problematic new synbath dataset in https://github.com/GenericMappingTools/gmtserver-admin/issues/213 warn us to always backup the old dataset before updating. I think we should have four directories:

- `data`: the directory for the "oceania" server
- `candidate`: the directory for working on the dataset updates 
- `test`: the test server that will be used by GMT tests
- `olddata` (or other names): the directory that contains the old server

When we update an existing dataset or adding a new dataset, we should first copy them to the `candidate` directory. If the dataset looks good, then we should move the dataset from "data" to "olddata" before copying them from "candidate" to "data". It's a little complicated, but it makes sure that we can quickly revert back to the correct "old" dataset if the updated dataset have issues (like #213).

> 7. A directory (maybe called reference or read-only or testdata) will be placed in _candidate_ so that these are not mirrored anywhere.

I don't understand this point. 

> 8. I will make some simple changes in gmt_remote.c so that when server is test then it inserts a /reference or similar string in the URL so we fish from the reference directory when running our test in CI or locally.

I'm a little confused about this point, too. From your points 7 and 8, are you suggesting adding a `reference` directory in both _candidate_ and _test_ server? What are the files in the `reference` directory?

**Comment by PaulWessel** [comment] 2023-08-23 14:31
Yes EarthScope sorry.  We do them lots of favours with the GMT for Geodesy course so they better help us out.

Yes, data_6.2 serves no function either so we can eliminate that as well and just have data.

The complication re 7-8 has to do with some limit of what SOEST can do.  Right now we have two redirects (oceania and test) to different subdirectories on the same server (gmtserver.soest.hawaii.edu).  It would of course be cleaner if we can simply add 2 more: candidate and  old data.  Then we would not have to hunt for directories inside others, etc.  Let me as IT if that is possible (cleaner for us) or what the issue is.

**Comment by PaulWessel** [comment] 2023-08-23 15:11
I notice that something earlier we had IT set up static.generic-mapping-tools.org for the purpose of using the static reference data that wont change when we do tests.  Since already set up we can have oceania, static (many take over for test) and add candidate?  I dont think we need old data.generic... since a make file will do stuff like moving things around on the server.

**Comment by PaulWessel** [comment] 2023-08-23 15:30
Didn't this use to work?

curl -L data.generic-mapping-tools.org:/gmt_data_server.txt

**Comment by seisman** [comment] 2023-08-24 00:07
> Since already set up we can have oceania, static (many take over for test) and add candidate?

Sounds good to me.

**Comment by seisman** [comment] 2023-09-09 02:52
It seems that oceanic, candidate and static are all online now. Does this mean we can remove the old earth_relief_2.1 directory from the main server?

**Comment by PaulWessel** [comment] 2023-09-09 07:33
Let's hear from @Esteban82 who has done a lot of the work. @federico, what remains, if anything on the server(s)? My though was that we placed all the new and updated stuff on candidate, then when 6.5 is released we update oceania with everything on candidate.

**Comment by PaulWessel** [comment] 2023-09-09 08:09
@seisman, you may have answered this before, but cannot recall:

When the CI runs all the tests, from where does it pull @earth_relief_XXXX etc?  Current oceania or some cached files before any updates?  I am hoping we can put what is compatible on the static server and then we need to pass static.generic-mapping-tools.org when running tests.  This will eliminate any data differences and then we can focus on actual failures - it is too hard to get 70-80 failures and many are data driven,

**Comment by seisman** [comment] 2023-09-09 08:16
We have a workflow that downloads the GMT remote data from the oceania server and stores them as GitHub Action cache files. The cache files will then be used by the tests.

**Comment by PaulWessel** [comment] 2023-09-09 08:18
OK, so this happens each time the full test is run? I.e., the cache is updated at that time so if I test with oceania we are using the same version?

**Comment by seisman** [comment] 2023-09-09 08:21
No, the workflow is scheduled to run once every week (https://github.com/GenericMappingTools/gmt/actions/workflows/ci-caches.yml). If you make any changes to oceania, then we have to _manually_ trigger the workflow to update the caches. After that, you and the CI will use the same version.

**Comment by PaulWessel** [comment] 2023-09-09 09:20
Wrote a script that determines which remote files are used in our doc and test scripts.  Got these 35 (some are the same since without registration we default to _p:

```
@earth_age_02m
@earth_age_02m_p
@earth_age_06m
@earth_age_06m_p
@earth_age_10m
@earth_age_10m_p
@earth_day_01d
@earth_day_01m
@earth_day_01m_p
@earth_day_15m
@earth_relief_01d
@earth_relief_01d_g
@earth_relief_01m
@earth_relief_01m_p
@earth_relief_02m
@earth_relief_02m_p
@earth_relief_03s
@earth_relief_04m
@earth_relief_04m_p
@earth_relief_05m
@earth_relief_05m_g
@earth_relief_05m_p
@earth_relief_06m
@earth_relief_06m_p
@earth_relief_10m
@earth_relief_10m_g
@earth_relief_10m_p
@earth_relief_15m
@earth_relief_15m_p
@earth_relief_20m
@earth_relief_20m_g
@earth_relief_30m
@earth_relief_30m_p
@earth_relief_30s
@earth_relief_30s_p
```

Perhaps we should just place these on the static server (copy from oceania for now) and see how that goes with testing that server?
Also, @joa-quim has a point that why use 01m tiles unless the bug is specific to tiling or high-res tiling.  If it works for 01m, 05m and 06m then we should simplify the tests and use 06m instead.  This means updating some PS files in DVC.
The doc scripts and examples may use what they use since we want nice images and not blurry ones.

**Comment by seisman** [comment] 2023-09-09 09:24
> Perhaps we should just place these on the static server (copy from oceania for now) and see how that goes with testing that server?

Sounds good to me.

**Comment by Esteban82** [comment] 2023-09-09 11:47
> Let's hear from @Esteban82 who has done a lot of the work. @federico, what remains, if anything on the server(s)? My though was that we placed all the new and updated stuff on candidate, then when 6.5 is released we update oceania with everything on candidate.

Yes, I think that we can delete from:

- Oceania: earth_relief2.1.
- Candidate: [earth_relief2.1/](http://candidate.generic-mapping-tools.org/server/earth/earth_relief2.1/) and [earth_relief2.5/](http://candidate.generic-mapping-tools.org/server/earth/earth_relief2.5/)

**Comment by PaulWessel** [comment] 2023-09-09 11:52
Great, can you take care of removing those? Then candidate is fully loaded (venus, moon etc)?

**Comment by Esteban82** [comment] 2023-09-09 12:09
> Great, can you take care of removing those?

From both servers, right?

> Then candidate is fully loaded (venus, moon etc)?

Yes

**Comment by PaulWessel** [comment] 2023-09-09 12:12
Yes, from oceania and candidate since we don't reference 2.1 anywhere

**Comment by Esteban82** [comment] 2023-09-09 13:04
@PaulWessel you will have to delete `earth_relief2.5` 

```
-bash-4.2$ rm -r earth_relief2.5/
rm: cannot remove ‘earth_relief2.5/earth_relief_03s_g/N44E004.earth_relief_03s_g.nc’: Permission denied
rm: cannot remove ‘earth_relief2.5/earth_relief_03s_g/N44E003.earth_relief_03s_g.nc’: Permission denied
rm: cannot remove ‘earth_relief2.5/earth_relief_03s_g’: Directory not empty

```
I deleted `earth_relief2.1` in both sites.

**Comment by PaulWessel** [comment] 2023-09-09 13:08
Thanks, and sorry, I see the 3s had incomplete permissions for the group...

**Comment by Esteban82** [comment] 2023-09-09 13:15
> I deleted `earth_relief2.1` in both sites.

We delete like 51GB from the server. Joaquim must be happy.

**Comment by Esteban82** [comment] 2023-09-09 13:33
I think we should also remove earth_relief2.1 and 2.5 from the test as well. It is better to leave it tidy

**Comment by PaulWessel** [comment] 2023-09-09 13:37
Yes, I think test is just for crazy experiments with new things until that dataset is stable and can go on candidate.  So please clean!

**Comment by Esteban82** [comment] 2023-09-09 13:41
> So please clean!

I deleted earth_relief2.1. For the 2.5 I don't have group permissions.

**Comment by PaulWessel** [comment] 2023-09-09 13:47
OK everything under test should now have group permissions rw, so you should be able to delete

**Comment by Esteban82** [comment] 2023-09-09 13:51
I have a doubt. Should I delete that directory or everything?

**Comment by PaulWessel** [comment] 2023-09-09 13:57
You mean "test" itself? No, let that one sit empty but server etc goes

**Comment by Esteban82** [comment] 2023-09-09 14:02
Ok, so I will delete everything inside the [server directory](http://test.generic-mapping-tools.org/server/).

**Comment by Esteban82** [comment] 2023-09-09 14:40
Done. But I still can't deleted these files.

```
-bash-4.2$ pwd
/export/gmtserver/gmt/test/server
-bash-4.2$ rm -r *
rm: cannot remove ‘earth/earth_relief2.5/earth_relief_03s_g/N44E004.earth_relief_03s_g.nc’: Permission denied
rm: cannot remove ‘earth/earth_relief2.5/earth_relief_03s_g/N44E003.earth_relief_03s_g.nc’: Permission denied
rm: cannot remove ‘earth/earth_relief2.5/earth_relief_03s_g’: Directory not empty
```

**Comment by Esteban82** [comment] 2023-09-09 14:44
Should I aslo delete the files within `/export/gmtserver/gmt/test/cache` ?

**Comment by PaulWessel** [comment] 2023-09-09 15:10
Yep

**Comment by Esteban82** [comment] 2023-09-10 12:37
Just deleted the files in `cache`.

**Comment by seisman** [comment] 2023-09-12 00:37
I think we can close the issue.

**Closed by seisman** 2023-09-12 00:37 UTC
